# Generated by Django 4.0 on 2022-02-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('field_type', models.CharField(db_column='_type', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('production_countries', models.CharField(max_length=200)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('overview', models.CharField(blank=True, max_length=2000, null=True)),
                ('now_status', models.CharField(blank=True, max_length=100, null=True)),
                ('flatrate', models.CharField(blank=True, max_length=100, null=True)),
                ('rent', models.CharField(blank=True, max_length=100, null=True)),
                ('buy', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsEpisodes',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('season_num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(db_column='NUMBER')),
                ('air_date', models.DateField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('overview', models.CharField(blank=True, max_length=2000, null=True)),
                ('still_path', models.CharField(blank=True, max_length=200, null=True)),
                ('crew', models.CharField(blank=True, max_length=1000, null=True)),
                ('guests', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'contents_episodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsReview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_like', models.IntegerField(db_column='_like')),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=1000)),
                ('field_datetime', models.DateTimeField(db_column='_datetime')),
            ],
            options={
                'db_table': 'contents_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsSeasons',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=100, primary_key=True, serialize=False)),
                ('air_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(db_column='NUMBER')),
                ('overview', models.CharField(blank=True, max_length=2000, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'contents_seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInterworking',
            fields=[
                ('i_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=20)),
                ('profile_name', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('simple_login', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_interworking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('overview', models.CharField(blank=True, max_length=200, null=True)),
                ('coin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchingLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('time_log', models.TimeField()),
            ],
            options={
                'db_table': 'watching_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('field_type', models.CharField(db_column='_type', max_length=10)),
                ('state', models.IntegerField()),
                ('wish_date', models.DateField()),
            ],
            options={
                'db_table': 'wish_list',
                'managed': False,
            },
        ),
    ]
