# Generated by Django 4.0 on 2022-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_genre', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=100)),
                ('c_release_date', models.DateField()),
                ('c_cast', models.CharField(max_length=200)),
                ('c_platform', models.CharField(max_length=100)),
                ('c_information', models.TextField()),
                ('c_preview_url', models.CharField(blank=True, max_length=200, null=True)),
                ('c_number', models.IntegerField(blank=True, null=True)),
                ('c_age_limit', models.CharField(blank=True, max_length=20, null=True)),
                ('c_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsReview',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_like', models.IntegerField()),
                ('cr_rating', models.FloatField()),
                ('cr_review', models.TextField()),
            ],
            options={
                'db_table': 'contents_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interworking',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_ott_name', models.CharField(max_length=20)),
                ('i_ott_id', models.CharField(max_length=20)),
                ('i_ott_passwd', models.CharField(max_length=20)),
                ('i_ott_profile', models.CharField(max_length=20)),
                ('i_profile_pwd', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'interworking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jjim',
            fields=[
                ('j_id', models.AutoField(primary_key=True, serialize=False)),
                ('j_state', models.IntegerField()),
                ('j_date', models.DateField()),
            ],
            options={
                'db_table': 'jjim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('u_passwd', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=20)),
                ('u_nickname', models.CharField(max_length=20)),
                ('u_gender', models.IntegerField()),
                ('u_age', models.IntegerField()),
                ('u_subs', models.CharField(blank=True, max_length=100, null=True)),
                ('u_information', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchingLog',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_time', models.TimeField()),
            ],
            options={
                'db_table': 'watching_log',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
